[font]
size = 10.0

[window]
opacity = 0.60

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black   = "#1d1f21"
red     = "#ff3c00"
green   = "#b9ca4a"
yellow  = "#e78c45"
blue    = "#7aa6da"
magenta = "#c397d8"
cyan    = "#70c0b1"
white   = "#eaeaea"

[colors.bright]
black   = "#969896"
red     = "#ff3c00"
green   = "#b9ca4a"
yellow  = "#e78c45"
blue    = "#7aa6da"
magenta = "#c397d8"
cyan    = "#70c0b1"
white   = "#ffffff"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular" 

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "ExtraBold"
